export const institutions = [
  "Indian Institute of Technology (IIT) Dhanbad (ISM Dhanbad)",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Advanced Manufacturing Technology (NIFFT) Ranchi",
  "Birla Institute of Technology (BIT) Mesra, Ranchi",
  "Indian Institute of Information Technology (IIIT) Ranchi",
  "Birla Institute of Technology (BIT) Deoghar",
  "Usha Martin University, Ranchi",
  "Jharkhand Rai University, Ranchi",
  "Sarala Birla University, Ranchi",
  "Ranchi University",
  "Central University of Jharkhand, Ranchi",
  "Jharkhand University of Technology, Ranchi",
  "Nilamber-Pitamber University, Medininagar",
  "Vinod Bihari Mahto Koyalanchal University, Dhanbad",
  "Amity University Jharkhand",
  "AISECT University, Ranchi",
  "RVS College of Engineering and Technology, Jamshedpur",
  "Cambridge Institute of Technology, Ranchi",
  "K.K. College of Engineering and Management, Dhanbad",
  "Rungta College of Engineering and Technology, Ranchi",
  "Government Engineering College, Vaishali",
  "Chaibasa Engineering College",
  "Bokaro Institute of Technology",
  "D.A.V Institute of Engineering and Technology, Palamau",
  "Guru Govind Singh Educational Society Technical Campus, Bokaro",
  "Maryland Institute of Technology and Management, Jamshedpur",
  "R.T.C Institute of Technology, Ranchi",
  "Ramgovind Institute of Technology, Koderma",
  "B.A College of Engineering and Technology, Jamshedpur",
  "Nilgai Education Trust's Group of Institutions, Ranchi",
  "Alice Institute of Technology, Ranchi",
  "Srinath University, Ranchi",
  "KK College of Engineering and Management, Dhanbad",
  "BIT Sindri, Dhanbad",
  "Netaji Subhas University, Jamshedpur",
  "Capital University, Ranchi",
  "Birsa Krishi Vishwavidyalaya, Ranchi",
  "Radha Govind University, Ranchi",
  "Ramchandra Chandravanshi University, Ranchi",
  "YBN University, Ramgarh",
  "Ramgarh Engineering College",
  "ICFAI University, Jharkhand",
  "ARKA JAIN University",
  "Sai Nath University",
  "Netaji Subhas Institute of Hotel Management and Tourism",
  "Khandoli Institute of Technology, Giridih",
  "Girija Institute of Polytechnic, Ramgarh",
  "Institute of Science and Management, Ranchi",
  "K.K. Polytechnic, Dhanbad",
  "BITT Polytechnic, Ranchi",
  "Cambridge Institute of Polytechnic, Ranchi",
  "Al-Kabir Polytechnic, Jamshedpur",
  "Centre for Bioinformatics, Ranchi",
  "Government Polytechnic, Bhaga, Dhanbad",
  "Jalandhar DAV Institute of Engineering and Technology",
  "Gyan Ganga Institute of Technology and Sciences, Jabalpur",
];
